-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 14:15:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ssmv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ssmv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssmv` DEFAULT CHARACTER SET utf8 ;
USE `ssmv` ;

-- -----------------------------------------------------
-- Table `ssmv`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`usuarios` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` CHAR(2) NOT NULL,
  `idfacebook` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idfacebook_UNIQUE` (`idfacebook` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`cronograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`cronograma` (
  `idcronograma` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `dataInicial` DATE NOT NULL,
  `dataFinal` DATE NOT NULL,
  `horarioInicial` TIME NOT NULL,
  `horarioFinal` TIME NOT NULL,
  `horarioIntervaloInicial` TIME NULL DEFAULT NULL,
  `horarioIntervaloFinal` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcronograma`),
  INDEX `fk_cronograma_usuarios_idx` (`idusuario` ASC),
  CONSTRAINT `fk_cronograma_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`notificacao` (
  `idnotificacao` INT(11) NOT NULL AUTO_INCREMENT,
  `de` INT(11) NOT NULL,
  `para` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `mensagem` VARCHAR(500) NOT NULL,
  `data` DATE NOT NULL,
  `resposta` TINYINT(4) NOT NULL DEFAULT '0',
  `visualizado` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idnotificacao`),
  INDEX `fk_notificacao_de_usuarios_idx` (`de` ASC),
  INDEX `fk_notificacao_para_usuarios_idx` (`para` ASC),
  CONSTRAINT `fk_notificacao_de_usuarios`
    FOREIGN KEY (`de`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_para_usuarios`
    FOREIGN KEY (`para`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 198
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`agendamentos` (
  `idagendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario_pf` INT(11) NOT NULL,
  `idusuario_pj` INT(11) NOT NULL,
  `idcronograma` INT(11) NOT NULL,
  `idnotificacao` INT(11) NOT NULL,
  PRIMARY KEY (`idagendamento`),
  INDEX `fk_agendamentos_usuarios_idx` (`idusuario_pf` ASC),
  INDEX `fk_agendamentos_cronograma_idx` (`idcronograma` ASC),
  INDEX `fk_agendamentos_notificacao_idx` (`idnotificacao` ASC),
  INDEX `fk_agendamentos_pj_usuarios_idx` (`idusuario_pj` ASC),
  CONSTRAINT `fk_agendamentos_cronograma`
    FOREIGN KEY (`idcronograma`)
    REFERENCES `ssmv`.`cronograma` (`idcronograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_notificacao`
    FOREIGN KEY (`idnotificacao`)
    REFERENCES `ssmv`.`notificacao` (`idnotificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_pf_usuarios`
    FOREIGN KEY (`idusuario_pf`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_pj_usuarios`
    FOREIGN KEY (`idusuario_pj`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`contato` (
  `idcontato` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `assunto` TEXT NOT NULL,
  PRIMARY KEY (`idcontato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`estados` (
  `idestado` INT(11) NOT NULL AUTO_INCREMENT,
  `sigla` CHAR(2) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`marcador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`marcador` (
  `idmarcador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(70) NOT NULL,
  `idestado` INT(11) NOT NULL,
  `telefone1` VARCHAR(10) NOT NULL,
  `telefone2` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(60) NOT NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idmarcador`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`tiposangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`tiposangue` (
  `idtipoSangue` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoSangue`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`pf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`pf` (
  `idusuario` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(90) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `idestado` INT(11) NOT NULL,
  `municipio` VARCHAR(70) NOT NULL,
  `telefoneF` VARCHAR(10) NOT NULL,
  `telefoneC` VARCHAR(11) NOT NULL,
  `idtipoSangue` INT(11) NOT NULL,
  `peso` FLOAT NOT NULL,
  `ultimaDoacao` DATE NOT NULL DEFAULT '1901-01-01',
  `foto` LONGBLOB NULL DEFAULT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  INDEX `idtipoSanguineo_idx` (`idtipoSangue` ASC),
  INDEX `fk_pf_estado_idx` (`idestado` ASC),
  CONSTRAINT `fk_pf_estado`
    FOREIGN KEY (`idestado`)
    REFERENCES `ssmv`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pf_tipoSangue`
    FOREIGN KEY (`idtipoSangue`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pf_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`pj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`pj` (
  `idusuario` INT(11) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `nomeFantasia` VARCHAR(90) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `idestado` INT(11) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `telefoneF` VARCHAR(10) NOT NULL,
  `telefoneF2` VARCHAR(10) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_pj_estado_idx` (`idestado` ASC),
  INDEX `fk_pj_usuarios_idx` (`idusuario` ASC),
  CONSTRAINT `fk_pj_estado`
    FOREIGN KEY (`idestado`)
    REFERENCES `ssmv`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pj_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`questionario` (
  `idusuario` INT(11) NOT NULL,
  `resp1` TINYINT(4) NOT NULL,
  `resp2` TINYINT(4) NOT NULL,
  `resp3` TINYINT(4) NOT NULL,
  `resp4` TINYINT(4) NOT NULL,
  `resp5` TINYINT(4) NOT NULL,
  `resp6` TINYINT(4) NOT NULL,
  `resp7` TINYINT(4) NOT NULL,
  `resp8` TINYINT(4) NOT NULL,
  `resp9` TINYINT(4) NOT NULL,
  `resp10` TINYINT(4) NOT NULL,
  `resp11` TINYINT(4) NOT NULL,
  `resp12` TINYINT(4) NOT NULL,
  `resp13` TINYINT(4) NOT NULL,
  `resp14` TINYINT(4) NOT NULL,
  `resp15` TINYINT(4) NOT NULL,
  `resp16` TINYINT(4) NOT NULL,
  `resp17` TINYINT(4) NOT NULL,
  INDEX `fk_questionario_usuarios_idx` (`idusuario` ASC),
  CONSTRAINT `fk_questionario_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`requisicao` (
  `idrequisicao` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipoSangue` INT(11) NOT NULL,
  `dataSolicitacao` DATE NOT NULL,
  `dataLimite` DATE NOT NULL,
  `urgencia` VARCHAR(5) NOT NULL,
  `idmarcador` INT(11) NOT NULL,
  PRIMARY KEY (`idrequisicao`),
  INDEX `fk_requisicao_tipoSangue_idx` (`tipoSangue` ASC),
  INDEX `fk_requisicao_usuarios_idx` (`idusuario` ASC),
  CONSTRAINT `fk_requisicao_tipoSangue`
    FOREIGN KEY (`tipoSangue`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requisicao_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ssmv`.`usuarios` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`sanguedoador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`sanguedoador` (
  `idsangueDoador` INT(11) NOT NULL,
  `idsangueCompativel` INT(11) NOT NULL,
  INDEX `fk_sangueDoador_idsangueCompativel_tipoSangue_idx` (`idsangueCompativel` ASC),
  INDEX `fk_sangueDoador_idsangueDoador_tipoSangue_idx` (`idsangueDoador` ASC),
  CONSTRAINT `fk_sangueDoador_idsangueCompativel_tipoSangue`
    FOREIGN KEY (`idsangueCompativel`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sangueDoador_idsangueDoador_tipoSangue`
    FOREIGN KEY (`idsangueDoador`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssmv`.`sanguerecebedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssmv`.`sanguerecebedor` (
  `idsangueRecebedor` INT(11) NOT NULL,
  `idsangueCompativel` INT(11) NOT NULL,
  INDEX `fk_sangueRecebedor_idsangueCompativel_tipoSangue_idx` (`idsangueCompativel` ASC),
  INDEX `fk_sangueDoador_idsangueDoador_tipoSangue_idx` (`idsangueRecebedor` ASC),
  CONSTRAINT `fk_sangueRecebedor_idsangueCompativel_tipoSangue`
    FOREIGN KEY (`idsangueCompativel`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sangueRecebedor_idsangueRecebedor_tipoSangue`
    FOREIGN KEY (`idsangueRecebedor`)
    REFERENCES `ssmv`.`tiposangue` (`idtipoSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
